### ISSUE TITLE
How to use in setup in ant design vue 2.x <a-table> Ask for help

### ISSUE THREAD

**Issue by nshusr** [SortableJS/vue.draggable.next#4]
How to use in setup in ant design vue 2.x

use composition-api 

<a-table>

https://2x.antdv.com/components/table/

:component

How to define the columns

 Ask for help  🤦

**Comment by David-Desmaisons** [comment]
For vue.2 use https://github.com/SortableJS/Vue.Draggable

**Comment by nshusr** [comment]
> For vue.2 use https://github.com/SortableJS/Vue.Draggable

"ant design vue 2.x" not is "vue 2.x" 😆

**Comment by David-Desmaisons** [comment]
> "ant design vue 2.x" not is "vue 2.x" 😆
Then maybe they should change its name because as it is, it is confusing.

There are some example on this repo on how to integrate vue.draggable with third party component using the tag props. You should start from here.
Once you have a propotype, if you have some dificulties to make it work you should use a stack-overflow question.
